# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticalTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'Kingfisher', '~> 5.13.4'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift', '~> 6.5.5'
  # Pods for PracticalTest
  pod "BSImagePicker", "~> 3.1"
  target 'PracticalTestTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'PracticalTestUITests' do
    # Pods for testing
  end
  
end
